language: go
go:
- 1.10.x
- master
branches:
  only:
  - develop
  - master
matrix:
  allow_failures:
  - go: master
install:
  - env GO111MODULE=on go get github.com/naoina/toml
  - env GO111MODULE=on go get github.com/pkg/errors
script:
  - env GO111MODULE=on go build -v ./...
